import { container } from "tsyringe";

import { PetsApi } from "@/autogenerated";
import { apiConfig } from "@/driver/apiconfig";

import { PetUseCase } from "@/application/usecase/pet";

container.register("PetApi", { useValue: new PetsApi(apiConfig) });

export const petUseCase = container.resolve<PetUseCase>(PetUseCase);
