import React, { useEffect } from "react";
import { PetsApi } from "@/autogenerated";
import { apiConfig } from "@/driver/apiconfig";

import { container } from "tsyringe";
import { PetUseCase } from "@/application/usecase/pet";

const Home: React.FC = ({}) => {
  useEffect(() => {
    container.register("PetApi", { useValue: new PetsApi(apiConfig) });
    const userUseCase = container.resolve<PetUseCase>(PetUseCase);

    (async () => {
      console.log(await userUseCase.list());
    })();
  }, []);

  return <></>;
};

export default Home;
