import React, { useEffect, useState } from "react";
import { PetsApi } from "@/autogenerated";
import { apiConfig } from "@/driver/apiconfig";

import { container } from "tsyringe";
import { PetUseCase } from "@/application/usecase/pet";
import { Pet } from "@/domain/inventory/pet";

import Home, { HomeProps } from "./presentational";

const useHomeProps = (): HomeProps => {
  const [pets, setPets] = useState<Pet[]>([]);

  useEffect(() => {
    container.register("PetApi", { useValue: new PetsApi(apiConfig) });
    const userUseCase = container.resolve<PetUseCase>(PetUseCase);

    (async () => {
      setPets(await userUseCase.list());
    })();
  }, []);

  return {
    pets: pets,
  };
};

const Container: React.FC = ({}) => {
  const props = useHomeProps();
  return <Home {...props} />;
};

export default Container;
