import { Configuration, ConfigurationParameters } from "@/autogenerated";

const configParams: ConfigurationParameters = {
  basePath: "http://localhost:3100",
  middleware: [],
};

export const apiConfig = new Configuration(configParams);
